SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE ADD_USER_LOG
(
	@LOG_ID BIGINT = 0,
	@USER_SESSION_ID NVARCHAR(30) = '',
	@USER_DOMAIN NVARCHAR(300) = '',
	@USER_BROWSER NVARCHAR(50) = '',
	@USER_PLATFORM NVARCHAR(30) = '',
	@USER_LOCATION NVARCHAR(60) = '',
	@REQUEST_TYPE VARCHAR(10) = '',
	@REQUEST_PAGE NVARCHAR(300) = '',
	@REQUEST_REFERER NVARCHAR(300) = '',
	@REQUEST_CONTENT_SIZE BIGINT = 0,
	@RESPOSE_STATUS INT = 0,
	@REQUEST_START_TIME DATETIME = NULL,
	@REQUEST_END_TIME DATETIME = NULL,
	@PROCESSING_TIME DECIMAL(10,10) = 0
)
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO USER_LOGS
	(
		USER_SESSION_ID,
		USER_DOMAIN,
		USER_BROWSER,
		USER_PLATFORM,
		USER_LOCATION,
		REQUEST_TYPE,
		REQUEST_PAGE,
		REQUEST_REFERER,
		REQUEST_CONTENT_SIZE,
		RESPOSE_STATUS,
		REQUEST_START_TIME,
		REQUEST_END_TIME,
		PROCESSING_TIME,
		LOG_CREATED_AT
	)
	VALUES
	(
		@USER_SESSION_ID,
		@USER_DOMAIN,
		@USER_BROWSER,
		@USER_PLATFORM,
		@USER_LOCATION,
		@REQUEST_TYPE,
		@REQUEST_PAGE,
		@REQUEST_REFERER,
		@REQUEST_CONTENT_SIZE,
		@RESPOSE_STATUS,
		@REQUEST_START_TIME,
		@REQUEST_END_TIME,
		@PROCESSING_TIME,
		GETDATE()
	)
END
GO
