USE [HONEY_POTS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [USER_LOGS]
(
	[LOG_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_SESSION_ID] [nvarchar](30) NULL,
	[USER_DOMAIN] [nvarchar](300) NULL,
	[USER_BROWSER] [nvarchar](50) NULL,
	[USER_PLATFORM] [nvarchar](30) NULL,
	[USER_LOCATION] [nvarchar](60) NULL,
	[REQUEST_TYPE] [varchar](10) NULL,
	[REQUEST_PAGE] [nvarchar](300) NULL,
	[REQUEST_REFERER] [nvarchar](300) NULL,
	[REQUEST_CONTENT_SIZE] [bigint] NULL,
	[RESPOSE_STATUS] [int] NULL,
	[REQUEST_START_TIME] [datetime] NULL,
	[REQUEST_END_TIME] [datetime] NULL,
	[PROCESSING_TIME] [decimal](10, 10) NULL,
	[LOG_CREATED_AT] [datetime] NULL,
	CONSTRAINT [PK_USER_INFO] PRIMARY KEY CLUSTERED ([LOG_ID] ASC)
)

GO